---
$schemaver: 2.0
repo_url: https://github.com/byu-oit/handel
software:
  - name: handel
    type: Command-line App
    aliases:
    short_description: Automated AWS deployments from a declarative spec file.
    assignment_group: gro:AD-Global Education Initiative
    notes:
    maintained_by:
      - dsw88
    developed_by_byu: true
    ddd:
        business_domain:
        ubiquitous_language_url:
        context_map_url:
    links:
        system_documentation_url: https://github.com/byu-oit/handel
        swagger_urls:
    microservice: false
    technologies_used:
      - JavaScript
      - Shell
    stages:
        production:
            urls:
                product_page: https://github.com/byu-oit/handel
                physical_url:
                virtual_url:
            hosting_location:
            aws_account:
            relationships:
                depends_on:
                    db_read_write:
                    db_read_only:
                    software:
                supports:
                    software:
                    service:
                reverse_proxy:
                runs_on:
                    server_cluster:
                    virtual_server:
                    rack_server:
                    blade_server:
    tags:
        data-sensitivity: confidential
        app: handel
        team: gro:AD-Global Education Initiative
