$schemaver: 2.1
repo_url: https://github.com/byu-oit/handel
software:
  - name: handel
    type: Command-line App
    aliases:
    short_description: Automated AWS deployments from a declarative spec file.
    assignment_group: gro:AD-Global Education Initiative
    notes:
    maintained_by:
      - dsw88
      - ndpete
      - byujol
      - jhermann21
      - ThatJoeMoore
    developed_by_byu: true
    links:
      system_documentation_url: https://github.com/byu-oit/handel
    microservice: false
    technologies_used:
      - JavaScript
      - Shell
      - CircleCI.com
      - NodeJS
      - TypeScript
      - HTML
    data_sensitivity: public
