version: 1
name: dynamodb-test
environments:
  dev:
    webapp:
      type: dynamodb
      table_name: exampletablename
      partition_key:
        name: partitionKeyName
        type: number
      sort_key:
        name: sortKeyName
        type: string
      provisioned_throughput:
        read_capacity_units: 5
        write_capacity_units: 5
        read_target_units: 70
        write_target_utilization: 65
      ttl_attribute: None
      local_indexes:
      - name: localIndexName
        sort_key:
          name: sortKeyName
          type: number
        attributes_to_copy:
        - someAttributeToCopy
      stream_view_type: KEYS_ONLY
      global_indexes:
      - name: globalIndexName
        partition_key:
          name: partitionKeyName2
          type: string
        sort_key: 
          name: sortKeyName2
          type: string
        attributes_to_copy: 
        - exampleAttributesToCopy2
        provisioned_throughput:
          read_capacity_units: 6
          write_capacity_units: 6
          read_target_units: 60
          write_target_utilization: 55
        event_consumers:
          - service_name: function
          batch_size: 100
        tags:
          mytagname: mytagvalue