---
AWSTemplateFormatVersion: '2010-09-09'
Description: Handel-created Aurora RDS instance

Parameters:
  DBUsername:
    NoEcho: true
    Description: The username of the database
    Type: String
  DBPassword:
    NoEcho: true
    Description: The password of the database
    Type: String

Resources:
  # ParameterGroup:
  #   Type: AWS::RDS::DBClusterParameterGroup
  #   Properties:
  #     Description: {{description}}
  #     Family: {{parameterGroupFamily}}
  #     {{#if parameterGroupParams}}
  #     Parameters:
  #       {{#each parameterGroupParams}}
  #       {{@key}}: '{{this}}'
  #       {{/each}}
  #     {{/if}}
  #     Tags:
  #     {{#if tags}}
  #     {{#each tags}}
  #     - Key: {{@key}}
  #       Value: {{this}}
  #     {{/each}}
  #     {{/if}}
  #     - Key: Name
  #       Value: {{stackName}}

  Cluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DatabaseName: {{databaseName}}
      DBClusterIdentifier: {{stackName}}
      DBClusterParameterGroupName: default.aurora-mysql5.7
      DBSubnetGroupName:  {{dbSubnetGroup}}
      Engine: {{engine}}
      EngineVersion: {{engineVersion}}
      Port: {{port}}
      Tags:
      {{#if tags}}
      {{#each tags}}
      - Key: {{@key}}
        Value: {{this}}
      {{/each}}
      {{/if}}
      - Key: Name
        Value: {{stackName}}
      VpcSecurityGroupIds:
      - {{dbSecurityGroupId}}

  {{#each instances}}
  DatabaseInstance{{@index}}:
    Type: AWS::RDS::DBInstance
    Properties:
      AllowMajorVersionUpgrade: true
      AutoMinorVersionUpgrade: true
      DBClusterIdentifier: !Ref Cluster
      DBInstanceClass: {{instanceType}}
      DBInstanceIdentifier: {{../stackName}}-{{@index}}
      # DBParameterGroupName: !Ref ParameterGroup
      DBSubnetGroupName: {{../dbSubnetGroup}}
      Engine: {{../engine}}
      PubliclyAccessible: false # TODO - This won't work when deploying DBs in public subnets?
      Tags:
      {{#if ../tags}}
      {{#each ../tags}}
      - Key: {{@key}}
        Value: {{this}}
      {{/each}}
      {{/if}}
      - Key: Name
        Value: {{../stackName}}

  {{/each}}

Outputs:
  ClusterEndpoint:
    Description: The connection endpoint of the Aurora cluster
    Value: !GetAtt Cluster.Endpoint.Address
  ClusterPort:
    Description: The port of the Aurora cluster
    Value: !GetAtt Cluster.Endpoint.Port
  ClusterReadEndpoint:
    Description: The read endpoint for the Aurora cluster
    Value: !GetAtt Cluster.ReadEndpoint.Address
  DatabaseName:
    Description: The name of the database
    Value: {{databaseName}}
